= JavaScript、函式、非同步

== 運算相關

=== Ternary Operator

=== Nullish Coalescing Operator/Assignment

=== Falsy

=== Custom Error

== 變數與作用域

=== var/let/const 差異

=== Hoisting

=== Temporal Dead Zone, TDZ

== 函式

=== Immediately Invoked Function Expression, IIFE

=== 高階函式 Higher-Order Function

=== 閉包 Closure

=== this

=== Arrow Function

== 非同步

=== 同步/非同步差異

=== XMLHttpRequest/fetch

=== AJAX

=== Promise
一個異步操作的最終完成（或失敗）及其結果值。 +

在 Promise 出現之前，JavaScript 中的異步操作主要透過**回調函數**來實現。 +
但回調函數的方式存在一些問題，例如**回調地獄問題**（也稱為"波動拳問題"）。 +

`Promise` 的出現解決了回調地獄問題，讓代碼更加清晰，易於理解。 +

[source,javascript]
----
// 回調地獄
callback(() => {
  console.log("Hello!");
  callback(() => {
    console.log("Hello!");
    callback(() => {
      console.log("Hello!");
      callback(() => {
        console.log("Hello!");
      }, 200);
    }, 200);
  }, 200);
}, 200);
----

`Promise` 是一個構造函式，需要透過 `new` 來建立一個 Promise 實例。 +
`Promise` 會接收一個被稱為 `executor` 的函式作為參數。 +

[source,javascript]
----
new Promise((resolve, reject) => {
  console.log("executor 立即執行"); // executor 立即執行
});
----

`executor` 函式會立即執行，並接收兩個參數，分別是 `resolve` 與 `reject`。 +
`resolve` 和 `reject` 是用來表示 Promise 的最終狀態。

* `resolve` 用來表示 Promise 成功完成，並且返回結果值。
* `reject` 用來表示 Promise 失敗，並且返回錯誤原因。

[source,javascript]
----
function requestData(url) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      if (url === "explainthis.io") {
        resolve("hello welcome to explain this");
      } else {
        reject("it is not explain this");
      }
    }, 3000);
  });
}

// 1. 請求成功
requestData("explainthis.io").then((res) => {
    console.log(res); //hello welcome to explain this
});

// 2. 請求失敗
requestData("explainthis.com").catch((e) => {
    console.log(e); //it is not explain this
});
----

Promise 的狀態只有三種，並且一定處於這三種狀態中的一種：

* `pending`: 初始狀態，既不是成功，也不是失敗。
* `fulfilled`: 表示操作成功完成。
* `rejected`: 表示操作失敗。

image::images//Promise.png[Promise 狀態]

`Promise` 通過 `then` 方法和 `catch` 方法解決了回調地獄問題，並且 `then` 可以鏈式調用，這使得代碼更具可讀性。

[source,javascript]
----
(function() {
  function requestData(url) {
    return new Promise((resolve, reject) => {
      setTimeout(() => {
        if (url === "explainthis.io") {
          resolve("hello welcome to explainthis");
        } else {
          reject("it is not explainthis");
        }
      }, 3000);
    });
  }

  requestData("explainthis.io")
    .then((res) => {
      console.log(res); //hello welcome to explainthis
      return 1;
    })
    .then((res) => {
      console.log(res); // 1
      return 2;
    })
    .then((res) => {
      console.log(res); // 2
    })
    .catch((e) => {
      console.log(e); //it is not explainthis
    });
})();
// 如果在控制台中輸入帶有 .then() 和 .catch() 的多行語句，它可能會在還未輸入完整的語句時執行，導致錯誤。
// 因此這裡改為使用匿名函數包裹函數，以避免這種情況。
----

`finally` 方法不管 Promise 狀態如何最後都會執行，並且不接收任何參數。 +

使用情境例如，一進入頁面就要顯示 loading，不管成功或失敗都要關閉 loading。 +
這時就可以使用 `finally` 方法。
[source,javascript]
----
fetch("https://explainthis.com/data")
  .then((response) => response.json())
  .then((data) => {
    console.log(data);
  })
  .catch((error) => {
    console.error(error);
  })
  .finally(() => {
    console.log("close loader");
  });
// 因為explainthis.com/data實際上不存在，所以會進入catch，最後執行finally
----

常用的Promise操作有：

* `Promise.all()`: 只有當所有 Promise 都成功時才會成功，一個失敗就會失敗。

[source,javascript]
----
var p1 = Promise.resolve(3);
var p2 = 1337;
var p3 = new Promise((resolve, reject) => {
    setTimeout(resolve, 100, "foo");
});

Promise.all([p1, p2, p3]).then((values) => {
    console.log(values); 
});

//From console:
// [3, 1337, "foo"]
----

* `Promise.allSettled()`: 等待所有 Promise 都完成（無論成功或失敗），都會回傳。

[source,javascript]
----
const promise1 = new Promise((resolve, reject) => {
    reject("fails 1");
});

const promise2 = new Promise((resolve, reject) => {
    setTimeout(resolve, 500, "resolve 1");
});

const promise3 = new Promise((resolve, reject) => {
    setTimeout(resolve, 100, "resolve 2");
});

Promise.allSettled([promise1, promise2, promise3]).then((value) => {
    console.log(value);
});

/*
From console:
[
  {"status":"rejected","reason":"fails 1"},
  {"status":"fulfilled","value":"resolve 1"},
  {"status":"fulfilled","value":"resolve 2"}
]
*/
----

* `Promise.any()`: 只要有一個 Promise 最先執行成功就會回傳最先執行成功的Promise結果，並且不會等待其他 Promise

[source,javascript]
----
const pErr = new Promise((resolve, reject) => {
  reject("總是失敗");
});

const pSlow = new Promise((resolve, reject) => {
  setTimeout(resolve, 500, "最終完成");
});

const pFast = new Promise((resolve, reject) => {
  setTimeout(resolve, 100, "很快完成");
});

Promise.any([pErr, pSlow, pFast]).then((value) => {
  console.log(value);
  // pFast 第一個resloved，所以輸出 "很快完成"
});
// 輸出：
// 很快完成
----

* `Promise.race()`: 只要有一個 Promise 完成（無論成功或失敗）就會回傳其結果。

[source,javascript]
----
var p1 = new Promise(function (resolve, reject) {
    setTimeout(resolve, 500, "one");
});
var p2 = new Promise(function (resolve, reject) {
    setTimeout(resolve, 100, "two");
});

Promise.race([p1, p2]).then(function (value) {
    console.log(value); // "two"
    // Both resolve, but p2 is faster
});

var p3 = new Promise(function (resolve, reject) {
    setTimeout(resolve, 100, "three");
});
var p4 = new Promise(function (resolve, reject) {
    setTimeout(reject, 500, "four");
});

Promise.race([p3, p4]).then(
    function (value) {
        console.log(value); // "three"
        // p3 is faster, so it resolves
    },
    function (reason) {
        // Not called
    },
);

var p5 = new Promise(function (resolve, reject) {
    setTimeout(resolve, 500, "five");
});
var p6 = new Promise(function (resolve, reject) {
    setTimeout(reject, 100, "six");
});

Promise.race([p5, p6]).then(
    function (value) {
        // Not called
    },
    function (reason) {
        console.log(reason); // "six"
        // p6 is faster, so it rejects
    },
);
----

=== async/await

`async/await` 是一種讓異步（非同步）操作更容易理解和管理的語法。它建立在 Promise 的基礎上，但提供了更簡潔、更直觀的方式來處理異步操作。

==== `async` 函數

* `async` 函數是一個返回 Promise 的函數，而非直接返回函式執行結果。

* 下方的普通函式 `f1()` 會直接返回字串 `"Hello! ExplainThis!"`：

[source,javascript]
----
function f1() {
  return "Hello! ExplainThis!";
}

f1(); // 輸出: "Hello! ExplainThis!"
----

* 而 `async` 函數 `f2()` 會返回一個 Promise 物件，並且 Promise 的狀態是 `fulfilled`，返回值是 `"Hello! ExplainThis!"`：

[source,javascript]
----
async function f2() {
  return "Hello! ExplainThis!";
}

f2(); // 輸出: Promise {<fulfilled>: 'Hello! ExplainThis!'}
----

* 下方程式碼與上方程式碼的寫法是相同的，因為使用 `async` 函數時，會自動將返回值包裝成 Promise 物件：

[source,javascript]
----
function f3() {
  return Promise.resolve("Hello! ExplainThis!");
}

f3(); // 輸出: Promise {<fulfilled>: 'Hello! ExplainThis!'}
----

由於 `async` 函數返回的是 Promise 對象，所以可以使用 `then` 方法進行鏈式調用：

[source,javascript]
----
async function f2() {
  return "Hello! ExplainThis!";
}

f2().then((result) => {
  console.log(result); // "Hello! ExplainThis!"
});
----

==== `await` 運算子

`await` 是一個運算子，用於等待一個 Promise 完成或拒絕。它只能在 `async` 函數中或模組的頂層使用。

* 當使用 `await` 運算子時，會暫停當前 `async` 函數的執行，直到 `await` 後的 Promise 完成或拒絕：

[source,javascript]
----
async function getData() {
  const res = await fetch("https://example.com/data");
  const data = await res.json();
  console.log(data);
}

getData();
----

=== 使用注意事項

* `await` 只能在 `async` 函數中使用，否則會拋出 **SyntaxError** 錯誤：

[source,javascript]
----
function f() {
  let promise = Promise.resolve("Hello! ExplainThis!");
  let result = await promise;
}

// Uncaught SyntaxError: await is only valid in async functions and the top level bodies of modules
----

* **頂層 `await`** 是 JavaScript 中引入的新功能，允許在模組的頂層使用 `await` 運算子：

[source,javascript]
----
const data = await getData();
// ...使用data
----

* `await` 會等待 Promise 完成，若 Promise 被拒絕，`await` 會拋出拒絕的值並中斷當前 `async` 函數的執行：

[source,javascript]
----
async function f() {
  try {
    let promise = Promise.reject("Hello! ExplainThis!");
    let result = await promise;
  } catch (e) {
    console.log(e); // "Hello! ExplainThis!"
  }
}

f();
----

* `await` 只能等待 Promise 物件，如果不是 Promise 物件，`await` 會將其轉換為已解析的 Promise：

[source,javascript]
----
async function f() {
  let result = await "Hello! ExplainThis!";
  console.log(result); // "Hello! ExplainThis!"
}

f();
----

* `await` 會等待 Promise 完成，但不會阻塞事件循環：

[source,javascript]
----
async function f() {
  console.log("Start");
  let result = await new Promise((resolve) => {
    setTimeout(() => {
      resolve("Hello! ExplainThis!");
    }, 1000);
  });
  console.log(result); // "Hello! ExplainThis!"
  console.log("End");
}

f();
// 輸出：
// Start
// End
// Hello! ExplainThis!
----

* `await` 可以與 `Promise.all()` 一起使用，以等待多個 Promise 同時完成：

[source,javascript]
----
async function f() {
  const [result1, result2] = await Promise.all([
    new Promise((resolve) => setTimeout(() => resolve("Hello!"), 1000)),
    new Promise((resolve) => setTimeout(() => resolve("ExplainThis!"), 2000)),
  ]);
  console.log(result1); // "Hello!"
  console.log(result2); // "ExplainThis!"
}

f();
// 輸出：
// Hello!
// ExplainThis!
----

使用 `async/await` 可以將異步程式碼寫成同步的形式，使得程式碼更加清晰易讀。

==== 使用範例

先來看一個使用 `Promise` 的例子：

[source,javascript]
----
function getData(url) {
  return new Promise((resolve, reject) => {
    fetch(url)
      .then((res) => res.json())
      .then((data) => resolve(data))
      .catch((error) => reject(error));
  });
}

getData("https://example.com/data")
  .then((data) => console.log(data))
  .catch((error) => console.error(error));
// 無法執行，因為實際上並沒有example.com/data這個網址，僅供參考
----

使用 `async/await` 重寫：

[source,javascript]
----
async function getData(url) {
  try {
    const res = await fetch(url);
    const data = await res.json();
    console.log(data);
  } catch (error) {
    console.error(error);
  }
}

getData("https://example.com/data");
// 無法執行，因為實際上並沒有example.com/data這個網址，僅供參考
----

在這個例子中：

. 使用 `async` 關鍵字定義一個異步函式，該函式會返回一個 `Promise` 對象。
. 在異步函式中，使用 `await` 等待 `Promise` 的完成，並直接返回結果。
. 使用 `try...catch` 捕獲異步操作中的錯誤，使得錯誤處理更加方便和直觀。

可以看出，使用 `async/await` 能夠使異步程式碼更加簡潔、易讀。

==== `async/await` 與 `Promise` 的比較

* **語法**: `async/await` 提供了更簡潔、更直觀的語法，使得異步程式碼更易讀和維護。`Promise` 則需要使用 `then` 和 `catch` 方法來處理結果和錯誤，語法上較為冗長。
* **錯誤處理**: 在 `async/await` 中，可以直接使用 `try...catch` 來捕獲錯誤，而在 `Promise` 中需要使用 `catch` 方法。
* **程式碼流程**: `async/await` 可以使異步程式碼看起來更像同步程式碼，更容易閱讀和理解。`Promise` 的程式碼流程則較為不連貫。


=== try…​catch 與非同步
